name: lint, testing, build
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  pipeline:
    runs-on: windows-2019
    strategy:
      matrix:
        node-version: ['20.x']

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - name: install modules
        run: npm install
      - name: build production frontend
        run: npm run build:prod
      - name: lint typescript
        run: npm run lint:ts
      - name: lint css
        run: npm run stylelint:check
      - name: unit testing
        run: npm run unit
      - name: storybook build
        run: npm run build-storybook
      - name: ui screenshot testing
        run: npm run test:ui:ci